### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by redyolocraft** [Aerion/uptobox-dl#9] opened 2023-05-15 04:28 UTC
Salut, j'ai une requête à formuler, mais je ne suis pas sûr de l'endroit approprié pour le faire, alors je la pose ici. Tout d'abord, permettez-moi de vous exprimer ma gratitude pour le travail que vous effectuez et également pour l'augmentation du délai d'attente. Serait-il possible que le logiciel puisse télécharger tous les fichiers d'un dossier Uptobox si je lui donne un lien correspondant ? De plus, serait-il envisageable de créer un fichier contenant tous les liens que je fournis au logiciel, de sorte que si le programme s'arrête, je puisse le relancer avec un paramètre permettant de reprendre là où il s'est arrêté ? Serait-il également possible que si le programme se termine de manière inattendue, il puisse se relancer avec cette option ?

Hello, I have a features request, but I'm not sure where to do it, so I'm asking it here. First of all, allow me to express my gratitude for the work you are doing and also for extending the timeout period. Would it be possible for the software to download all the files from an Uptobox folder if I provide a corresponding link? Additionally, would it be feasible to create a file containing all the links I provide to the software, so that if the program stops, I can relaunch it with a parameter to resume from where it left off? Would it also be possible that if the program crashes, it can restart with this option?

**Comment by Aerion** [comment] 2023-05-15 17:18
Hi,
Thanks for the ideas :)
I'll keep the messages in English for future readers.

> Would it be possible for the software to download all the files from an Uptobox folder if I provide a corresponding link?

It's feasible and should be relatively simple to implement according to https://docs.uptobox.com/?javascript#retrieve-files-in-public-folder

> Additionally, would it be feasible to create a file containing all the links I provide to the software, so that if the program stops, I can relaunch it with a parameter to resume from where it left off?
> Would it also be possible that if the program crashes, it can restart with this option?

Does it occur often that the program crashes and that one needs to restart it by resuming?
I'm not sure about the additional complexity for a "simple" download tool.

By any chance, would you be willing to implement one of the above features?
Cheers

**Comment by Aerion** [comment] 2023-05-18 13:25
The new version [v1.3.0](https://github.com/Aerion/uptobox-dl/releases/tag/v1.3.0) handles uptobox folder links 🎉
I also added some retry mechanism to hopefully reduce the crashes you mentioned when uptobox fails to respond.
Feel free to try it out!

**Comment by Aerion** [comment] 2023-05-19 09:54
Thanks, I removed the mail from the yopmail inbox after grabbing the link.

I don't have any issue on my end with the link you provided:

```
$ ./uptobox-dl -t <REDACTED> 'https://uptobox.com/user_public?hash=<REDACTED>&folder=<REDACTED>'
8 files to download (from 0 direct links and 1 folders)
Start processing <REDACTED>
66256604B/880534047B: 7%
```

Could you please share the output of the same command you did, but by passing the `--verbose --debug` flags? e.g. 
`./uptobox-dl -t <REDACTED> 'https://uptobox.com/user_public?hash=<REDACTED>&folder=<REDACTED>' --verbose --debug`

What will be of interest is the following
```
Getting uri: https://uptobox.com/api/user/public?folder=<REDACTED>&hash=<REDACTED>&limit=100&offset=0
Deserialized data: {"statusCode":0,"message":"Success","data":{"list":[{"file_name":" (...)
```

If you were to call it with the url `https://uptobox.com/user_public?hash=fooooooooo&folder=baaaaaaaar`, you should see 
```
Getting uri: https://uptobox.com/api/user/public?folder=baaaaaaaar&hash=fooooooooo&limit=100&offset=0
```

On which OS are you running uptobox-dl, is it Windows, Linux?
Maybe you could try running the command by putting the link in single quotes like my example above?

**Comment by Aerion** [comment] 2023-05-19 12:58
I see, the issue is that uptobox-dl is not receiving the full commandline because of the `&` character.
Are you using powershell or cmd.exe as a command prompt?
See https://stackoverflow.com/questions/1327431/how-do-i-escape-ampersands-in-batch-files

Could you try to put the link in double quotes `"https://...&folder=..."`? Or to run it from powershell maybe?

To confirm it, try doing `echo https://uptobox.com/user_public?hash=REDACTED&folder=REDACTED`, you'll see the same error, wheras if it's quoted or run from powershell, you should have a single line being printed with `https://uptobox.com/user_public?hash=REDACTED&folder=REDACTED`.

**Comment by Aerion** [comment] 2023-05-19 13:05
To go back on the initial issue, I added a simple mechanism that I believe could match what you were asking with the resume behavior:
The new release [v.1.40](https://github.com/Aerion/uptobox-dl/releases/tag/v1.4.0) will skip over a file that was already downloaded (present on disk with the same name and size). So if you launch uptobox-dl with multiple links (or folders), stop it, and re-start it with the same links, only the new files (or the one that was not fully downloaded) will be processed!

**Comment by Aerion** [comment] 2023-05-19 13:11
Let's close it, and if you find other issues/new ideas, feel free to create new ones
Cheers :)

**Closed by Aerion** 2023-05-19 13:11 UTC
